---
title: "cell_ontology_structure"
output: html_document
date: "2023-02-09"
---
```{r}
curdir <- "/Users/kariyayama/Labolatory/JST_Mouse_Human/Tabula/Integration"
setwd(curdir)
library(here)
set_here(curdir)
library(rbioapi)
library(tidyverse)
library(SingleCellExperiment)
library(gridExtra)
library(cowplot)
library(ontoProc)
library(ontologyPlot)
library(Seurat)
source("run_seurat_GO_analysis.R")
```

Cell ontology
```{r}
cl <- get_OBO(
  "~/Labolatory/JST_Mouse_Human/Ontology/cl.obo", 
  extract_tags = "everything"
  )

# CLのうち、Parentsを抽出
convert_list_to_matrix <- function(x){
  cl$parents[x] %>%
    unlist -> parents
  parents[grep("^CL:", parents)] %>%
    as.character -> cl.parents
  cbind(rep(x, length(cl.parents)), cl.parents)
}

cl$id %>%
  unlist %>%
  as.character -> cl.id
cl.id[grep("^CL:", cl.id)] -> cl.id
result <- c()
for(id in cl.id){
    convert_list_to_matrix(id) %>%
        rbind(result, .) -> result
}
tibble(CL_ID = result[,1],
       CL_Parents = result[,2]) -> cl.parents
tibble(CL_ID = names(cl$name),
       CL_Name = cl$name) -> cl_name
cl_name[grep("^CL:", cl_name$CL_ID),] %>%
  inner_join(cl.parents, by = "CL_ID", multiple = "all") -> cl.name
```

無理やりCell ontologyをくっつけてみる
```{r}
tibble(CL_ID = "CL:0000000") %>%
    left_join(cl.parents, by = c("CL_ID" = "CL_Parents"),
              multiple = "all") %>% dplyr::rename(CL_ID_1 = CL_ID.y) %>%
    left_join(cl.parents, by = c("CL_ID_1" = "CL_Parents"),
              multiple = "all") %>% dplyr::rename(CL_ID_2 = CL_ID.y) %>%
    filter(CL_ID_1 == "CL:0000003") %>%
    left_join(cl.parents, by = c("CL_ID_2" = "CL_Parents"),
              multiple = "all") %>% dplyr::rename(CL_ID_3 = CL_ID) %>%
    left_join(cl.parents, by = c("CL_ID_3" = "CL_Parents"),
              multiple = "all") %>% dplyr::rename(CL_ID_4 = CL_ID) %>%
    left_join(cl.parents, by = c("CL_ID_4" = "CL_Parents"),
              multiple = "all") %>% dplyr::rename(CL_ID_5 = CL_ID) %>%
    left_join(cl.parents, by = c("CL_ID_5" = "CL_Parents"),
              multiple = "all") %>% dplyr::rename(CL_ID_6 = CL_ID) %>%
    left_join(cl.parents, by = c("CL_ID_6" = "CL_Parents"),
              multiple = "all") %>% dplyr::rename(CL_ID_7 = CL_ID) %>%
    left_join(cl.parents, by = c("CL_ID_7" = "CL_Parents"),
              multiple = "all") %>% dplyr::rename(CL_ID_8 = CL_ID) %>%
    left_join(cl.parents, by = c("CL_ID_8" = "CL_Parents"),
              multiple = "all") %>% dplyr::rename(CL_ID_9 = CL_ID) %>%
    left_join(cl.parents, by = c("CL_ID_9" = "CL_Parents"),
              multiple = "all") %>% dplyr::rename(CL_ID_10 = CL_ID) %>%
    left_join(cl.parents, by = c("CL_ID_10" = "CL_Parents"),
              multiple = "all") %>% dplyr::rename(CL_ID_11 = CL_ID) %>%
    left_join(cl.parents, by = c("CL_ID_11" = "CL_Parents"),
              multiple = "all") %>% dplyr::rename(CL_ID_12 = CL_ID) %>%
    left_join(cl.parents, by = c("CL_ID_12" = "CL_Parents"),
              multiple = "all") %>% dplyr::rename(CL_ID_13 = CL_ID) %>%
    left_join(cl.parents, by = c("CL_ID_13" = "CL_Parents"),
              multiple = "all") %>% dplyr::rename(CL_ID_14 = CL_ID) %>%
    left_join(cl.parents, by = c("CL_ID_14" = "CL_Parents"),
              multiple = "all") %>% dplyr::rename(CL_ID_15 = CL_ID) %>%
    left_join(cl.parents, by = c("CL_ID_15" = "CL_Parents"),
              multiple = "all") %>% dplyr::rename(CL_ID_16 = CL_ID) %>%
    left_join(cl.parents, by = c("CL_ID_16" = "CL_Parents"),
              multiple = "all") %>% dplyr::rename(CL_ID_17 = CL_ID) %>%
    left_join(cl.parents, by = c("CL_ID_17" = "CL_Parents"),
              multiple = "all") %>% dplyr::rename(CL_ID_18 = CL_ID) %>%
    filter(CL_ID_3 == "CL:0000548") %>%
    pivot_longer(cols = -c("CL_ID.x"),
                 names_to = "depth",
                 names_pattern = "CL_ID_(.*)",
                 values_to = "CL_depth") %>%
   filter(!is.na(CL_depth)) %>%
    mutate(depth = as.numeric(depth))-> cl.ontology

cl.ontology %>% 
    inner_join(cl_name, by = c("CL_depth" = "CL_ID")) %>% 
    dplyr::rename(root = CL_ID.x) -> cl_depth
cl_depth %>%
  write.table("cell_ontology_table.tsv", quote = F, sep = "\t", row.names = F)
```

Provitional cell ontology
```{r}
pcl = get_OBO("http://purl.obolibrary.org/obo/pcl.obo", extract_tags = "everything")
```

