---
title: "count_shared_marker_gene"
output: html_document
date: "2023-01-31"
---
# 細胞型間で共通しているマーカー遺伝子の数・割合を調べることで、共通の細胞型を知りたい
```{r}
library(RColorBrewer)
curdir <- "~/Labolatory/JST_Mouse_Human/Tabula/Integration"

# renv::restore()
setwd(curdir)
library(here)
set_here(curdir)
source("run_seurat_GO_analysis.R")
source("count_marker_gene_GO.R")
```
マーカー遺伝子一覧を用意
```{r}
organs <- c("Bladder", "Bone_Marrow", "Fat", "Heart", "Kidney", "Large_Intestine",
            "Liver", "Lung", "Pancreas", "Skin", "Spleen", "Thymus", "Trachea")
hs_marker <- tibble()
getwd()
for(input in organs){
    outdir <- paste(curdir, input, sep = "/")
    extract_cluster_label(input, "Hs") -> Hs_cluster_label
    read_marker_gene_list("Hs", input, "_") %>%
      select(cluster) %>%
      distinct %>%
      unlist %>%
      as.numeric -> Hs_all
    for(clstr in Hs_all){
        paste(outdir, "/Marker_gene/",
              "Hs_Mm_", input,
              ".seurat_integrate.cluster_", clstr, ".homology.tsv",
              sep = "") %>%
          read_tsv(show_col_types = FALSE) -> marker
        marker %>%
          mutate(organ = input) %>%
          transform(cluster = as.factor(cluster))%>%
          inner_join(Hs_cluster_label, by = c("cluster" = "integrated_seurat_cluster")) %>% 
          bind_rows(hs_marker, .) -> hs_marker
    }
}
```

細胞型間で共通するマーカー遺伝子をカウント
```{r}
cell_type_1.list <- c()
cell_type_2.list <- c()
gene_shared.list <- c()
gene1.only.list  <- c()
gene2.only.list  <- c()

hs_marker %>%
    mutate(cell_label = paste(organ, cluster, sep = "_")) -> hs_marker.label
hs_marker.label %>%
    select(cell_label) %>% distinct %>% unlist %>% as.character() -> cell_type_list
for(cell_type_1 in cell_type_list){
  for(cell_type_2 in cell_type_list){
    hs_marker.label %>%
      filter(cell_label == cell_type_1) %>%
      select(Gene_name) %>%
      distinct -> gene1
    hs_marker.label %>%
      filter(cell_label == cell_type_2) %>%
      select(Gene_name) %>%
      distinct  -> gene2
    inner_join(gene1, gene2, by = "Gene_name") %>%
      distinct  -> gene_shared
    anti_join(gene1, gene2, by = "Gene_name") %>%
      distinct  -> gene1.only
    anti_join(gene2, gene1, by = "Gene_name") %>%
      distinct  -> gene2.only
    cell_type_1.list <- c(cell_type_1.list, cell_type_1)
    cell_type_2.list <- c(cell_type_2.list, cell_type_2)
    gene_shared.list <- c(gene_shared.list, dim(gene_shared)[1])
    gene1.only.list  <- c(gene1.only.list,  dim(gene1.only)[1])
    gene2.only.list  <- c(gene2.only.list,  dim(gene2.only)[1])
  }
}

data.frame(cell_type_1 = cell_type_1.list,
           cell_type_2 = cell_type_2.list,
           Shared = gene_shared.list,
           Gene1_only = gene1.only.list,
           Gene2_only = gene2.only.list) %>%
  as_tibble -> shared_marker_count
write.table(shared_marker_count, "hs_shared_marker_gene.tsv",
            quote = F, sep = "\t", row.names = F)
```

可視化
```{r}
hs_marker.label %>%
  mutate(cell_ontology_class = str_split(customclassif, "_", simplify = T)[,2]) %>%
  inner_join(cell_ontology_sum, by = "cell_ontology_class") %>%
  mutate(customclassif = paste(Summarized_class, cell_label, sep = "_")) %>%
  select(customclassif, organ, cell_label) %>%
  distinct -> organ_cell.label

# 共通している割合の分布
shared_marker_count %>%
  mutate(ratio = Shared / (Shared + Gene1_only)) %>%
  mutate(label = paste(cell_type_1, cell_type_2, sep = "_")) %>%
  filter(cell_type_1 != cell_type_2) %>%
  ggplot(aes(x = reorder(label, ratio), y = ratio)) +
    geom_point()
# 共通している割合の分布をヒートマップにする
shared_marker_count %>%
  mutate(ratio = Shared / (Shared + Gene1_only)) %>%
  filter(cell_type_1 != cell_type_2 & ratio > 0.5) %>%
  ggplot(aes(x = reorder(cell_type_1, ratio),
             y = reorder(cell_type_2, ratio), fill = ratio)) +
    geom_tile()

shared_marker_count %>%
    mutate(ratio.1_2 = Shared / (Shared + Gene1_only),
           ratio.2_1 = Shared / (Shared + Gene2_only)) %>%
    filter(cell_type_1 != cell_type_2 & ratio.1_2 > 0.5 & ratio.2_1 > 0.5) %>%
    inner_join(organ_cell.label, by = c("cell_type_1" = "cell_label")) %>%
    inner_join(organ_cell.label, by = c("cell_type_2" = "cell_label")) %>%
    arrange(desc(ratio.2_1)) %>%
    ggplot(aes(x = reorder(customclassif.x, ratio.1_2),
               y = reorder(customclassif.y, ratio.2_1), fill = ratio.1_2 + ratio.2_1)) +
      geom_tile()  +
      theme_bw() +
      theme(axis.text.x =
              element_text(angle = 90, hjust = 1, vjust = 0.5)) +
      coord_fixed()
```

特定のペアに対して実行
```{r}
cell_type_1 <- "Bladder_0"
cell_type_2 <- "Bladder_1"
hs_marker.label %>%
  filter(cell_label == cell_type_1) %>%
  select(Gene_name) -> gene1
hs_marker.label %>%
  filter(cell_label == cell_type_2) %>%
  select(Gene_name) -> gene2
inner_join(gene1, gene2, by = "Gene_name") -> gene_shared
anti_join(gene1, gene2, by = "Gene_name") -> gene1.only
anti_join(gene2, gene1, by = "Gene_name") -> gene2.only

```