---
title: "GO_analysis"
output: html_document
date: "2023-01-26"
---
事前準備
```{r}
library(RColorBrewer)
curdir <- "~/Labolatory/JST_Mouse_Human/Tabula/Integration"

# renv::restore()
setwd(curdir)
library(here)
set_here(curdir)
source("run_seurat_GO_analysis.R")
source("count_marker_gene_GO.R")
```

グローバル変数
```{r}
test_type <- "FISHER"
cutoff <- 0.05
hsapiens <- 9606
mmuculus <- 10090
# BP <- "GO:0008150"
BP <- "ANNOT_TYPE_ID_PANTHER_GO_SLIM_BP"
header = "number_in_list\tfold_enrichment\tfdr\texpected \tnumber_in_reference\tpValue\tplus_minus\tterm.id\tterm.label"
types <- c("shared", "Hs_only") # + , "No_homology_info"
```

```{r}
# input <- "Liver"
# organs <- c("Bladder", "Bone_Marrow", "Fat", "Heart", "Kidney", "Large_Intestine",
#             "Liver", "Lung", "Muscle", "Pancreas", "Skin", "Spleen", "Thymus", "Trachea")
organs <- c("Muscle")
for(input in organs){
    outdir <- paste(curdir, input, sep = "/")
    paste(outdir, "PANTHER/Hs_shared-only", sep = "/") %>%
      dir.create()
    
    read_marker_gene_list("Hs", input, "_") %>%
      select(cluster) %>%
      distinct %>%
      unlist %>%
      as.numeric -> Hs_all
    for(clstr in Hs_all){
        paste(outdir, "/Marker_gene/",
              "Hs_Mm_", input,
              ".seurat_integrate.cluster_", clstr, ".homology.tsv",
              sep = "") %>%
          read_tsv(show_col_types = FALSE) -> marker
        
        for(type in types){
          print(paste(input, clstr, types))
          marker %>%
            filter(share == type) %>%
            select(Gene_name) %>%
            unlist %>%
            as.character -> marker.genes
          # Outfile
          outfile <- paste(outdir, "/PANTHER/Hs_shared-only/", 
                           "Hs_Mm_", input, ".seurat_integrate.cluster_", clstr, "_", type, ".tsv", 
                           sep = "")
          # GO analysis
          go_analysis(marker.genes, hsapiens)
          Sys.sleep(1)
        }
    }
}

```
integrate data from the result of GO analysis
```{r}
label.share <- c("Both", "Hs_only", "shared")
labelcolors <- colorRampPalette(brewer.pal(length(label.share),
                                           "Set2"))(length(label.share))
names(labelcolors) <- c("Both", "Hs_only", "shared")
```

```{r}
for(input in organs){
  outdir <- paste(curdir, input, sep = "/")
  read_marker_gene_list("Hs", input, "_") %>%
        select(cluster) %>%
        distinct %>%
        unlist %>%
        as.numeric -> Hs_all
  
  for(clstr in Hs_all){
    print(paste(input, clstr))
    # ファイル読み込み
    merged_shared_only(input, clstr) -> merged_table
    if(dim(merged_table)[1] > 0){
        merged_table %>%
          ggplot(aes(x = GO_short, y = fdr_log, fill = group)) +
          geom_bar(stat = "identity") +
          facet_grid(type ~ .) +
          theme_classic() +
          scale_fill_manual(values = labelcolors) +
          theme(axis.text.x =
                    element_text(angle = 90, hjust = 1, vjust = 0.5)) -> p1
      
      merged_table %>%
        group_by(GO_short) %>%
        select(GO_short) %>%
        distinct %>%
        dim -> go_term_num
      outfile <- paste(outdir, "/PANTHER/Hs_shared-only/Hs_compare_", input,"_ident_",
                       clstr, "_sharing.png", sep= "")
      ggsave(outfile, p1, width = go_term_num[1]*0.6+2, height = 14)
    }
  }
}
```
```{r}
input <- "Liver"
outdir <- paste(curdir, input, sep = "/")
read_marker_gene_list("Hs", input, "_") %>%
      select(cluster) %>%
      distinct %>%
      unlist %>%
      as.numeric -> Hs_all
human_organ <- tibble()
human_organ.selected <- tibble()

for(clstr in Hs_all){
    shared.ident <- tibble()
    read_GOanalysis_result(input, clstr, "shared") -> shared.ident
    only.ident <- tibble()
    read_GOanalysis_result(input, clstr, "Hs_only") -> only.ident
    
    integrated.shared <- tibble()
    if(dim(shared.ident)[1] > 0)
      integrate_species_sharing(shared.ident, only.ident,
                                "Shared", 50) %>%
      mutate(cell_label = paste(input, clstr,
                                sep = "_")) -> integrated.shared
    
    integrated.only <- tibble()
    if(dim(only.ident)[1] > 0)
      integrate_species_sharing(only.ident, shared.ident,
                                "Hs_only", 50) %>%
      mutate(cell_label = paste(input, clstr,
                                sep = "_")) -> integrated.only
    
    bind_rows(integrated.shared, integrated.only) %>%
      bind_rows(human_organ, .) -> human_organ
    merged_shared_only(input, clstr, n = 10) %>%
      select(GO_short) %>%
      bind_rows(human_organ.selected, .) %>%
      distinct -> human_organ.selected
}
```

```{r}
human_organ %>%
    inner_join(human_organ.selected, by = c("GO_short")) %>%
    filter(fdr_log > 0) %>%
    ggplot(aes(x = GO_short, y = cell_label, color = group)) +
    geom_point(size = 4) +
    theme_bw() +
    scale_color_manual(values = labelcolors) +
    theme(axis.text.x =
              element_text(angle = 90, hjust = 1, vjust = 0.5))
```

