---
title: "Disease_ontology"
output: html_document
date: "2023-02-10"
---
```{r}
curdir <- "/Users/kariyayama/Labolatory/JST_Mouse_Human/Tabula/Integration"
setwd(curdir)
library(here)
set_here(curdir)
library(rbioapi)
library(tidyverse)
library(SingleCellExperiment)
library(gridExtra)
library(cowplot)
library(ontoProc)
library(ontologyPlot)
library(Seurat)
source("run_seurat_GO_analysis.R")
```

```{r}
"hs_mm_marker_disease_human_gene.tsv" %>%
  read_tsv(show_col_types = FALSE) -> hs_mm_marker_disease
```
Ontologyを取得
```{r}
url <- "https://github.com/DiseaseOntology/HumanDiseaseOntology/raw/main/src/ontology/HumanDO.obo"
# hdo_2022_09 = get_OBO(url, extract_tags = "everything")
# saveRDS(hdo_2022_09, "../../Ontology/hdo.rds")
hdo_2022_09 <- readRDS("../../Ontology/hdo.rds")
# cl = getOnto("cellOnto", "2022") # for continuity --    has_high_plasma_membrane_amount: list
# do = getOnto("diseaseOnto", "2022")
# saveRDS(cl, "../../Ontology/cl.rds")
# saveRDS(do, "../../Ontology/do.rds")
cl <- readRDS("../../Ontology/cl.rds")
do <- readRDS("../../Ontology/do.rds")
```

DO情報を抽出
```{r}
# DO Name
tibble(DO_ID = names(hdo_2022_09$name),
       DO_name = unlist(hdo_2022_09$name)) -> DO_name
# DO define
tibble(DO_ID = names(hdo_2022_09$def),
       DO_def = as.character(unlist(hdo_2022_09$def))) -> DO_def
# DOのうち、is_aを抽出
convert_list_to_matrix <- function(x){
  x_name <- names(x)
  x %>%
    unlist %>%
    length -> i
  if(i > 0){
    x %>%
      unlist %>%
      as.character -> x_body
    cbind(rep(x_name, i), x_body)
  }
}
# is_a
result <- c()
for(i in 1:length(hdo_2022_09$is_a)){
    convert_list_to_matrix(hdo_2022_09$is_a[i]) %>%
        rbind(result, .) -> result
}
tibble(DO_ID = result[,1],
       Parents = result[,2]) %>% 
  distinct -> do_parents

# xref
result <- c()
for(i in 1:length(hdo_2022_09$xref)){
    convert_list_to_matrix(hdo_2022_09$xref[i]) %>%
        rbind(result, .) -> result
}
tibble(DO_ID = result[,1],
       xref = result[,2]) %>% 
  distinct -> do_xref

```

DOをis_aをもとに取得する
```{r}
hs_marker_disease %>%
  dplyr::select(DO_Disease_ID) %>%
  distinct -> hs_mm_do_id
hs_mm_do_id %>%
    dplyr::rename(DO_ID = DO_Disease_ID) %>%
    mutate(DO_ID_1 = DO_ID) %>%
    left_join(do_parents, by = c("DO_ID"),
              multiple = "all") %>% dplyr::rename(DO_ID_2 = Parents) %>%
    left_join(do_parents, by = c("DO_ID_2" = "DO_ID"),
              multiple = "all") %>% dplyr::rename(DO_ID_3 = Parents) %>%
    left_join(do_parents, by = c("DO_ID_3" = "DO_ID"),
              multiple = "all") %>% dplyr::rename(DO_ID_4 = Parents) %>%
    left_join(do_parents, by = c("DO_ID_4" = "DO_ID"),
              multiple = "all") %>% dplyr::rename(DO_ID_5 = Parents) %>%
    left_join(do_parents, by = c("DO_ID_5" = "DO_ID"),
              multiple = "all") %>% dplyr::rename(DO_ID_6 = Parents) %>%
    left_join(do_parents, by = c("DO_ID_6" = "DO_ID"),
              multiple = "all") %>% dplyr::rename(DO_ID_7 = Parents) %>%
    left_join(do_parents, by = c("DO_ID_7" = "DO_ID"),
              multiple = "all") %>% dplyr::rename(DO_ID_8 = Parents) %>%
    left_join(do_parents, by = c("DO_ID_8" = "DO_ID"),
              multiple = "all") %>% dplyr::rename(DO_ID_9 = Parents) %>%
    left_join(do_parents, by = c("DO_ID_9" = "DO_ID"),
              multiple = "all") %>% dplyr::rename(DO_ID_10 = Parents) %>%
    left_join(do_parents, by = c("DO_ID_10" = "DO_ID"),
              multiple = "all") %>% dplyr::rename(DO_ID_11 = Parents) %>%
    left_join(do_parents, by = c("DO_ID_11" = "DO_ID"),
              multiple = "all") %>% dplyr::rename(DO_ID_12 = Parents) %>%
    left_join(do_parents, by = c("DO_ID_12" = "DO_ID"),
              multiple = "all") %>% dplyr::rename(DO_ID_13 = Parents) %>%
    pivot_longer(cols = -c("DO_ID"),
                 names_to = "depth",
                 names_pattern = "DO_ID_(.*)",
                 values_to = "DO_depth") %>%
   filter(!is.na(DO_depth)) %>%
    mutate(depth = as.numeric(depth)) -> do_depth

# depthの表記を変更
do_depth %>%
  filter(DO_depth == "DOID:4") %>%
  dplyr::select(DO_ID, depth) %>%
  inner_join(do_depth, ., by = "DO_ID", multiple = "all") %>%
  mutate(depth = depth.y - depth.x + 1) %>%
  dplyr::select(DO_ID, depth, DO_depth) -> do_depth

do_depth %>% inner_join(DO_name, by = "DO_ID") %>% 
    dplyr::rename(Main_name = DO_name) %>%
    inner_join(DO_name, by = c("DO_depth" = "DO_ID")) %>% 
    dplyr::rename(Depth_name = DO_name) -> do_depth

write.table(do_depth, "Disease_ontology/do_is_a_table.tsv", sep = "\t", quote = F, row.names = F)
```


# Regacy

Disease Ontologyの準備
```{r}
extract_target_layer <- function(targets, n = 5){
  results <- c()
  for(term in targets){
    hdo_2022_09$ancestors[term] %>%
      unlist -> test
    results <- c(results, as.character(test[n]))
  }
  return(results)
}

# 全てのDOについて、Rootからの深さを調べる
hdo_2022_09$ancestors %>%
  sapply(length) -> depth
tibble(DO_Disease_ID=names(depth),
       depth = unlist(depth)) -> disease_depth
write.table(disease_depth,
            "Disease_ontology/do_depth.tsv",
            quote = F, row.names = F, sep = "\t")

# MGIデータに出てくるDOについて深さを調べる
hs_mm_marker_disease %>%
  inner_join(disease_depth,
             by = "DO_Disease_ID") -> hs_mm_disease_depth
disease_depth %>%
  dplyr::count(depth)
```


KEGGの疾病分類を使ってプロット
```{r}
read_tsv("KEGG/KEGG_Human_Disease.tsv",
         show_col_types = NA) %>% 
  mutate(low_name = tolower(Disease_name)) -> KEGG_disease

inner_join(merged_disease_table, DO_name,
           by = c("DO_Disease_ID" = "DO_ID"),
           multiple = "all") %>%
    dplyr::select(DO_small, DO_name) %>% distinct %>%
    mutate(low_name = tolower(DO_name)) -> Hs_Mm.DO_names

Hs_Mm.DO_names %>%
    inner_join(KEGG_disease, by = c("low_name"),
               multiple = "all") -> KEGG_DO
Hs_Mm.DO_names %>%
    anti_join(KEGG_disease, by = c("low_name")) %>%
    write.table("KEGG/DO_KEGG_no.tsv", sep = "\t", quote = F, row.names = F)

inner_join(merged_disease_table, DO_name,
    by = c("DO_small" = "DO_ID"),
    multiple = "all") %>%
    inner_join(KEGG_disease, by = c("DO_name" = ""))
    ggplot(aes(x=DO_ID, y = cell_ontology_label,
               color = cell_ontology_class)) +
    geom_point() +
    facet_grid(share ~ Label, space = "free", scales = "free") +
    theme_bw() +
    theme(axis.text.x =
              element_text(angle = 90, hjust = 1, vjust = 0.5),
          legend.position = "bottom") +
    NoLegend()
```


不要な記号やURLの情報を取り除きつつ、Definitionを抽出した
```{r}
bind_rows(disease_convert_table, disease_convert_table.threshold) %>%
  inner_join(DO_def, by = c("DO_small" = "DO_ID")) %>%
  select(DO_small, DO_def) %>%
  distinct -> hs_mm_disease_def
hs_mm_disease_def$DO_def %>%
  str_split("\"", simplify = T) %>%
  as.data.frame %>%
  select(V2) %>%
  mutate(V2 = tolower(V2)) %>% 
  mutate(V2 = str_replace_all(V2, "\\(", "")) %>%
  mutate(V2 = str_replace_all(V2, "\\)", "")) %>%
  mutate(V2 = str_replace_all(V2, "\\.", "")) %>%
  mutate(V2 = str_replace_all(V2, ",", "")) %>%
  mutate(words = str_split(V2, " ", simplify = T)) -> ontology_word_vector
ontology_word_vector$words %>%
  as.vector() %>%
  unique -> words
```

ワードベクトルの表を作成
```{r}
results <- c()
for(word in words){
  ontology_word_vector$words %>%
    apply(1, function(x) as.numeric(any(x == word))) %>%
    matrix(ncol = 1) -> word_vec
  colnames(word_vec) <- word
  results <- cbind(results, word_vec)
}
results %>% colSums -> results.sums
tibble(word = names(results.sums), sum = results.sums) %>%
  filter(sum > 4) %>%
  ggplot(aes(x=reorder(word, sum), y=sum)) +
    geom_bar(stat = "identity") +
  theme(axis.text.x = 
          element_text(angle = 90, hjust = 1, vjust = 0.5),  
        legend.position = "bottom")
tibble(word = names(results.sums), sum = results.sums) %>%
    dplyr::count(sum)
```




REGACY：いらなくなったけど、別のところで使えるかも？

```{r}
do_parents %>% filter(Parents == "DOID:4") %>% select(Parents, DO_ID) %>% inner_join(do_parents, by = c("DO_ID" = "Parents")) %>% inner_join(do_parents, by = c("DO_ID.y" = "Parents")) %>% inner_join(do_parents, by = c("DO_ID.y.y" = "Parents")) %>% inner_join(do_parents, by = c("DO_ID" = "Parents")) 
```

```{r}

# Test set: DOID:0110229, DOID:0081168, DOID:9296, DOID:0060055,DOID:0060239, DOID:0060776
target_doid <- "DOID:0110229"
count_layer <- function(target, do_list){
  target_doid <- target
  result <- c()
  i = 1
  if(target_doid[1] == "DOID:4"){
    return(c(target_doid[1], i, target_doid[1]))
  }
  while(target_doid[1] != "DOID:4"){
    do_parents %>%
      filter(DO_ID == target_doid[1]) %>%
      inner_join(do_list, by = c("Parents" = "DO_Disease_ID")) -> searched_result
    if(dim(searched_result)[1] != 0){
      return(i)
    }else{
      i <- i + 1
      do_parents %>%
        filter(DO_ID == target_doid[1]) %>%
        select(Parents) %>%
        unlist %>%
        as.character -> target_doid
    }
  }
}

count_layers <- function(targets, do_list = do_root){
  result <- c()
  for(target in targets){
      print(target)
      result <- c(result, count_layer(target, do_list)) 
  }
  return(result)
}
# REGACY
# 全てのDOについて、Rootからの深さを調べる
# tibble(DO_Disease_ID=c(do_parents$DO_ID,
#                do_parents$Parents)) %>%
#   distinct %>%
#   mutate(depth = count_layers(DO_Disease_ID,
#                               do_root)) -> disease_depth
```
とあるDO:IDの深さを調べる
```{r}
do_root <- tibble(DO_Disease_ID = c("DOID:4"))
```

特定の階層のものをとる
```{r}
upper_layer <- function(target, do_list){
  target_doid <- target
  i = 1
  while(target_doid[1] != noterm){
    do_parents %>%
      filter(DO_ID == target_doid[1]) %>%
      inner_join(do_list, by = c("Parents" = "DO_Disease_ID")) -> searched_result
    # print(searched_result)
    if(dim(searched_result)[1] != 0){
      do_parents %>%
        filter(DO_ID == target_doid[1]) %>%
        inner_join(do_list, by = c("Parents" = "DO_Disease_ID")) %>%
        select(Parents) %>%
        unlist %>% as.character %>% head(n=1) -> out
      return(out)
    }else{
      i <- i + 1
      do_parents %>%
        filter(DO_ID == target_doid[1]) %>%
        select(Parents) %>%
        unlist %>%
        as.character -> target_doid
      # print(target_doid)
    }
  }
}
noterm <- "DOID:4"
upper_layers <- function(targets, do_list = do_root){
  result <- c()
  for(target in targets){
    print(target)
    result <- c(result, upper_layer(target, do_list))
  }
  return(result)
}

disease_depth %>%
  filter(depth == 4) -> hs_mm_threshold

hs_mm_disease_depth %>%
  filter(depth < 5) %>%
  mutate(DO_small = DO_Disease_ID) -> disease_convert_table
hs_mm_disease_depth %>%
  filter(depth > 4) %>%
  mutate(DO_small = upper_layers(DO_Disease_ID,
                                 hs_mm_threshold)) -> disease_convert_table.threshold
```
depthを含めた表を作る
```{r}
count_layer <- function(target){
  target_doid <- target
  result <- c()
  i = 1
  if(target_doid[1] == "DOID:4"){
    return(c(target_doid[1], i, target_doid[1]))
  }
  while(target_doid[1] != "DOID:4"){
    do_parents %>%
      filter(DO_ID == target_doid[1]) %>%
      inner_join(do_list, by = c("Parents" = "DO_Disease_ID")) -> searched_result
    if(dim(searched_result)[1] != 0){
      return(i)
    }else{
      i <- i + 1
      do_parents %>%
        filter(DO_ID == target_doid[1]) %>%
        select(Parents) %>%
        unlist %>%
        as.character -> target_doid
        result <- cbind(c(""))
    }
  }
}
```


```{r}

```

