---
title: "Specificity index"
output: html_document
date: "2022-11-22"
---

```{r}
Hs_liver.picked@assays$RNA@data %>% apply(1, mean) -> mean.all_cells
```

```{r}
result <- c()
for(i in 0:14){
  # ident 0
  Hs_liver.picked@meta.data %>%
    rownames_to_column(var = "cell") %>%
    filter(Ident == i) %>%
    select("cell") %>%
    unlist -> Hs_cell.ident
  Hs_liver.picked@assays$RNA@data[, Hs_cell.ident] %>%
    apply(1, mean) %>%
    cbind(result, .) -> result
}
colnames(result) <- c("Ident0",  "Ident1",  "Ident2",  "Ident3",
                      "Ident4",  "Ident5",  "Ident6",  "Ident7",
                      "Ident8",  "Ident9",  "Ident10", "Ident11",
                      "Ident12", "Ident13", "Ident14")
```

```{r}
result[as.logical(rowSums(result)), ] -> result
result %>%
  apply(1, mean) %>%
  data.frame(means = ., gene = names(.))-> result.mean
result %>%
  as.data.frame %>%
  rownames_to_column(var = "gene") %>%
  inner_join(result.mean, by = "gene") %>%
  mutate(Ident0 = Ident0 / means,
         Ident1 = Ident1 / means,
         Ident2 = Ident2 / means,
         Ident3 = Ident3 / means,
         Ident4 = Ident4 / means,
         Ident5 = Ident5 / means,
         Ident6 = Ident6 / means,
         Ident7 = Ident7 / means,
         Ident8 = Ident8 / means,
         Ident9 = Ident9 / means,
         Ident10 = Ident10 / means,
         Ident11 = Ident11 / means,
         Ident12 = Ident12 / means,
         Ident13 = Ident13 / means,
         Ident14 = Ident14 / means
         ) %>%
  pivot_longer(-c(gene), names_to = Ident, values_to = SI) %>%
  ggplot(aes(x = Ident, y = SI, fill = Ident)) + 
    geom_violin()
```

