---
title: "Gene_age"
output: html_document
date: "2022-12-14"
---

```{r}
curdir <- "~/Labolatory/JST_Mouse_Human/Tabula/Integration"
# renv::restore()

setwd(curdir)
library(here)
set_here(curdir)
library(tidyverse)
library(scAlign)
library(Seurat)
library(SingleCellExperiment)
library(gridExtra)
library(cowplot)
read_tsv("~/Labolatory/JST_Mouse_Human/Tabula/Integration/Hs_Mm_one2one_genelist.tsv",
         show_col_types = FALSE) ->
  Hs_Mm
source(paste(curdir, "integration_analysis_function.R", sep = "/"))
```

解析に使う組織の選択
```{r}
input <- "Kidney"
outdir <- paste(curdir, input, sep = "/")
```

データの読み込み
```{r}
# ヒト
readRDS(file=paste(outdir, "/TS_", input, ".rds", sep = "")) -> Hs_seurat

Hs_cell <- celltype_pick(Hs_seurat)

Hs_seurat@assays$RNA@data %>%
  as.data.frame() %>%
  rownames_to_column(var = "Gene") -> Hs_seurat.data
Hs_seurat@meta.data %>%
  as.data.frame %>%
  rownames_to_column(var = "Cells") -> Hs_seurat.meta.data

Hs_seurat@reductions$umap@cell.embeddings %>%
  as.data.frame %>%
  rownames_to_column(var = "Cells") -> Hs_seurat.umap
```

Gene ageの読み込み
```{r}
hs_gene_age <- read_tsv("Gene_age/Hs_gene_age_Litman_Stein.txv",
                        show_col_types = FALSE) %>%
  dplyr::rename(Gene = HGNC) %>%
  dplyr::rename(Age = "modal value")
age_label <- read_csv("Gene_age/Litman_Stein.label.tsv", 
                      show_col_types = FALSE) %>%
  mutate(label = paste(Age, Phylo, sep = "_"))
```
```{r}
Hs_seurat.data %>%
    dplyr::select(c(1:5000)) %>%
    pivot_longer(-c("Gene"), names_to = "Cells", values_to = "count.norm") %>%
    inner_join(hs_gene_age, by = "Gene") %>%
    group_by(Cells) -> Hs_seurat.longer
```

TAI計算
```{r}
TAI <- function(seurat_data.longer, stock_cells = 2000){
  seurat_data.longer %>%
    group_by(Cells) %>%
    summarise(TAI = sum(count.norm * Age)/sum(count.norm))
}
Hs_tai <- TAI(Hs_seurat.longer, stock_cells = 5000)
```
UMAP・TAI・meta.dataデータ結合
```{r}
Hs_seurat.umap %>%
  inner_join(Hs_tai, by = "Cells") %>%
  inner_join(Hs_seurat.meta.data, by = "Cells") -> Hs.meta.data.tai
```
TAIプロット
```{r}
# UMAP
Hs.meta.data.tai %>%
  ggplot(aes(x = umap_1, y = umap_2, color = TAI)) +
  geom_point() -> Hs_tai.plot
Hs.meta.data.tai %>%
  ggplot(aes(x = umap_1, y = umap_2, color =  cell_ontology_class)) +
  geom_point() -> Hs_cell_ontology.plot
Hs_tai.plot | Hs_cell_ontology.plot

# Violinプロット
Hs.meta.data.tai %>%
  ggplot(aes(x=cell_ontology_class,
             y = TAI, fill = cell_ontology_class)) +
  geom_violin() +
  theme_classic() +
  NoLegend()
```
それぞれのAgeについて計算
```{r}
hs.each_age <- data.frame()
for(ident in unique(hs_gene_age$Age)){
  Hs_seurat.longer %>%
    filter(Age == ident) %>%
    summarise(count.mean = mean(count.norm)) %>%
    mutate(Age = ident) %>%
    bind_rows(hs.each_age, .) -> hs.each_age
}
```
最大と最小
```{r}
hs.each_age %>%
  group_by(Age) %>%
  summarise(count.max = max(count.mean),
            count.min = min(count.mean)) -> Hs_seurat.min_max
```
それぞれのAgeの合計発現量を他の情報と統合
```{r}
hs.each_age %>%
    inner_join(Hs_seurat.meta.data, by = "Cells") %>%
    inner_join(Hs_seurat.min_max, by = "Age") %>%
    mutate(relative = (count.mean - count.min) / (count.max - count.min)) %>%
    full_join(age_label, by = "Age") %>%
    transform(label= factor(label, levels = rev(age_label$label))) -> hs.each_age.relative
```
それぞれのAgeの合計発現量をバイオリンプロット→ボックスプロット
```{r}
hs.each_age.relative %>%
  ggplot(aes(y = cell_ontology_class,
             x = relative, fill = cell_ontology_class)) +
  facet_wrap(label ~ ., scale = "free", nrow = 5) +
  geom_boxplot() +
  theme_bw() +
  NoLegend()
```

```{r}
# read marker gene list
paste(outdir,
      "Marker_gene",
      "Hs_Kidney.seurat_integrate.celltype_pick_markergene.tsv", sep ="/") %>%
  read_tsv(show_col_types = FALSE) -> Hs_marker.kidney
```

